/*
* generated by Xtext
*/
package se.bjornkjellgren.ui.contentassist;

import se.bjornkjellgren.ui.contentassist.AbstractWeek1ProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class Week1ProposalProvider extends AbstractWeek1ProposalProvider {

}
