/*
 * generated by Xtext
 */
package se.bjornkjellgren.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Week1UiModule extends se.bjornkjellgren.ui.AbstractWeek1UiModule {
	public Week1UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
