/*
 * generated by Xtext
 */
package se.bjornkjellgren.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import se.bjornkjellgren.ui.internal.Week1Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Week1ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Week1Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Week1Activator.getInstance().getInjector(Week1Activator.SE_BJORNKJELLGREN_WEEK1);
	}
	
}
