/*
* generated by Xtext
*/
package se.bjornkjellgren;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class Week1UiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return se.bjornkjellgren.ui.internal.Week1Activator.getInstance().getInjector("se.bjornkjellgren.Week1");
	}
	
}
