/*
* generated by Xtext
*/
package se.bjornkjellgren.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class Week1OutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
