/*
 * generated by Xtext
 */
package se.bjornkjellgren;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Week1RuntimeModule extends se.bjornkjellgren.AbstractWeek1RuntimeModule {

}
